### ISSUE TITLE
Stable for Plone 4.3.4?

### ISSUE THREAD

**Issue by pgrunewald** [RedTurtle/collective.powertoken.workflow#1]
Hello keul,

beforehand, this is not a real issue. Your product sounds very fitting for my use case (publish content via link). I would like to know if it considered stable, especially for Plone 4.3.4? I'm asking since its depending product collective.powertoken.core is listed as _beta_ status on plone.org.

best regards

**Comment by keul** [comment]
Hi @pgrunewald,

powertoken has not been updated recently but should work normally on Plone 4.3 also.
Plus: is not registering nothing "dangerous" so you can easily remove it later if it doesn't fit your needs.

Suggestion: before digging in using it, take a look at https://github.com/redomino/redomino.tokenrole
